# Generated by Django 3.2.9 on 2021-12-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deposit',
            field=models.IntegerField(null=True),
        ),
    ]
