# Generated by Django 3.2.9 on 2021-12-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_profile_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
    ]
