# Generated by Django 3.2.9 on 2021-12-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20211202_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.CharField(default=0.0, max_length=15),
        ),
    ]
