# Generated by Django 3.2.9 on 2021-12-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_profile_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deposit',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
