# Generated by Django 3.2.9 on 2022-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountType',
            field=models.CharField(choices=[('Starter', 'Starter: $50 - $499'), ('Platinum', 'Platinum: $500 - $1,499'), ('Bronze', 'Bronze: $1,500 - $4,499'), ('Silver', 'Silver: $4,500 - $9,000'), ('Gold', 'Gold: $9,100 - $14,499'), ('Diamond', 'Diamond: $15,000 - $100,000')], max_length=300, null=True),
        ),
    ]
